server:
  port: 3001
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: false
    hostname: eureka3001.com
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http;//eureka3000.com:3000/eureka/