server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: false
    hostname: eureka3000.com
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka